### PR TITLE
Bumped Hue API swversion to 1941132080

### PR DESCRIPTION
**Pull request by xcorp**

### CODE REVIEW

**Review by marcelveldt — CHANGES_REQUESTED** [review]
Please remove the dummy file.
Was there a reason to set the data argument in the parser to str ? I believe that is the default...

**Comment by marcelveldt** [comment]
Thanks for the PR ! See my comments above

**Comment by xcorp** [comment]
Sorry, still kinda new to git/github, only the first commit where supposed to be in the pull request.
I haven't set the data argument to str, only added line brakes to comply with the black linter.

The Dummy file has been removed, was just to trigger the "on push" actions in github.

**Comment by marcelveldt** [comment]
Sorry for the trouble. The version was already updated by another PR/commit.
Thanks anyway !!

**Comment by Kvanr23** [comment]
@marcelveldt 
The version that you put in the definitions.json is not 1941132080, which this pull request was meant for. 
That version is not on the hue changelog page yet according to this [Reddit post](https://www.reddit.com/r/Hue/comments/k4t2ab/new_bridge_firmware_1941132080/).

I commented this because I keep getting the update prompt. 

P.S. Sorry for tagging 😀

**Comment by marcelveldt** [comment]
yeah I know. I'm about to merge a dev branch with a lot of fixes ;-)

**Comment by Kvanr23** [comment]
Ah, sorry then!

**Pull request closed without merging**
