### PR TITLE
Solution for åäö gets turned into ���.

### PR DESCRIPTION
**Pull request by thesymbol**
Sends the data that is non unicode directly instead of converting it to unicode first and then sending.
This solves the issue where åäö gets turned into ��� on android and empty text on iOS (personally tested on both platforms on the official app).
I have not tested third party apps except Hue Essentials, and seems to be working there as well.

After inspecting the API compared to a real Hue bridge with postman sending the same requests i got the following responses
Real Hue Bridge:
```
"1": {
        "name": "Kök",
        "lights": [
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10",
            "14"
        ],
        "sensors": [],
        "type": "Room",
        "state": {
            "all_on": true,
            "any_on": true
        },
        "recycle": false,
        "class": "Kitchen",
        "action": {
            "on": true,
            "bri": 253,
            "ct": 336,
            "alert": "none",
            "colormode": "ct"
        }
    },
```
Emulated Hue Bridge:
```
"4": {
        "class": "Kitchen",
        "lights": [
            "15",
            "16",
            "17",
            "18",
            "19",
            "20",
            "21",
            "22"
        ],
        "name": "K\u00f6k",
        "type": "Room"
    }
```

And with the changes in this pull request the \u00f6 gets replaced with the actual character ö like the real hue bridge.
So the result will now instead be the following:
```
"4": {
        "class": "Kitchen",
        "lights": [
            "15",
            "16",
            "17",
            "18",
            "19",
            "20",
            "21",
            "22"
        ],
        "name": "Kök",
        "type": "Room"
    }
```

Some final notes:

* this might impact other regions as well so needs to be tested by others, i doubt it will break for others but you never really know (since we don't really know how the app operates internally).
* There might be a better way of handling this, as i have not actually coded that much in python before (coming from a c#/asp.net background), so please if anything can be done in a better way tell me.

Solves Issue #19 and Issue #30

### CODE REVIEW

**Comment by marcelveldt** [comment]
Thanks for the PR, I'll take a look tomorrow as I've checked in a bunch of changes that are now conflicting.
Also I'm wondering if there's another fix for this such as a global setting in the json encoder.

**Comment by thesymbol** [comment]
Thanks for taking a look at it, pulled down your changes and merged them into my branch so there should no longer be any more merge conflicts.

**Comment by marcelveldt** [comment]
Thanks! I'm still wondering what's causing this. I can't remember ever have seen this issue with aiohttp and the default json encoder before. But if I remember correctly the standard for json is that strings are UTF-8 encoded so it might be that the Hue bridge implementation just doesn't follow the specs strictly.

**Comment by thesymbol** [comment]
Yep i think you are right, the hue bridge doesn't specify any encoding in its content-type either so we can not know for 100% certainty what encoding they are using.
But what we do know is that the app itself does not handle unicode conversion properly, at least on android it tries to read it but spits out the � symbol, but on iOS it just leaves the text blank.

**Comment by marcelveldt** [comment]
I could not come up with a better/other solution. The issue lies in the json encoder forcing ascii for unicode characters.
As far as I can see will your PR not create any side affects and it works as expected.

Thanks!!

**Pull request merged**
